apiVersion: v1
kind: Service
metadata:
  name: cipherledger-service
spec:
  type: LoadBalancer
  selector:
    app: cipherledger
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: p2p
      protocol: TCP
      port: 9000
      targetPort: 9000
