import { useState } from "react";
import { Key, ShieldCheck, ShieldAlert, FileText, Copy, Award, CheckCircle, RefreshCw } from "lucide-react";
import toast from "react-hot-toast";
import { simpleHash } from "../utils/mockBlockchain";

const bip39Words = [
  "cipher", "ledger", "entropy", "quantum", "crystal", "secure",
  "matrix", "nebula", "orbital", "plasma", "pulse", "vector",
  "vertex", "shadow", "galaxy", "stellar", "aurora", "vortex",
  "shield", "crypto", "kernel", "binary", "protocol", "beacon"
];

export default function CryptoPlayground() {
  // Section 1: HD Wallet Derivation
  const [mnemonic, setMnemonic] = useState([]);
  const [derivationPath, setDerivationPath] = useState("m/44'/60'/0'/0/0");
  const [derivedWallet, setDerivedWallet] = useState(null);

  // Section 2: Signature Generator
  const [signMessage, setSignMessage] = useState("");
  const [signPrivateKey, setSignPrivateKey] = useState("");
  const [generatedSignature, setGeneratedSignature] = useState("");

  // Section 3: Signature Verifier
  const [verifyMessage, setVerifyMessage] = useState("");
  const [verifyPublicKey, setVerifyPublicKey] = useState("");
  const [verifySignature, setVerifySignature] = useState("");
  const [verificationResult, setVerificationResult] = useState(null); // 'VALID' or 'INVALID'

  const copyToClipboard = (text, label) => {
    navigator.clipboard.writeText(text);
    toast.success(`${label} copied to clipboard!`);
  };

  // Generate 12 random mnemonic words
  const handleGenerateMnemonic = () => {
    const words = [];
    for (let i = 0; i < 12; i++) {
      const idx = Math.floor(Math.random() * bip39Words.length);
      words.push(bip39Words[idx]);
    }
    setMnemonic(words);
    setDerivedWallet(null);
    toast.success("New 12-word seed phrase generated.");
  };

  // Derive private, public keys and address from mnemonic + derivation path
  const handleDeriveKeys = () => {
    if (mnemonic.length === 0) {
      toast.error("Please generate or enter a mnemonic seed phrase first.");
      return;
    }
    const seedString = mnemonic.join(" ") + derivationPath;
    const privateKey = "prv_" + simpleHash(seedString);
    const publicKey = "pub_" + simpleHash(privateKey).substring(0, 40);
    const address = "CLD_" + simpleHash(publicKey).substring(0, 24).toUpperCase();

    setDerivedWallet({
      privateKey,
      publicKey,
      address
    });
    toast.success("Cryptographic keys successfully derived.");
  };

  // Sign message using private key (deterministic EC-like simulation)
  const handleSign = (e) => {
    e.preventDefault();
    if (!signMessage || !signPrivateKey) {
      toast.error("Message and Private Key required to generate signature.");
      return;
    }
    // Simulate ECDSA signature generation: Hash(Message + PrivateKey)
    const rawSig = simpleHash(signMessage + signPrivateKey);
    setGeneratedSignature(rawSig);
    toast.success("Signature generated successfully.");
  };

  // Verify signature
  const handleVerify = (e) => {
    e.preventDefault();
    if (!verifyMessage || !verifyPublicKey || !verifySignature) {
      toast.error("All verification fields are required.");
      return;
    }
    // Reconstruct expected signature simulation
    // A signature is valid if it matches our deterministic signing hash with the derived private key
    // For educational UI purposes, we verify if the signature represents Hash(Message + prvKey) 
    // where pubKey = Hash(prvKey). So if verifySignature == Hash(Message + prvKey), it is valid.
    // If the signature is a 64-hex string and corresponds to a signed hash, we evaluate validation.
    // For the UI simulation, we check if signature matches simpleHash(verifyMessage + PrivateKey).
    // To make it friendly: if verifySignature matches simpleHash(verifyMessage + "prv_" + verifyPublicKey.replace("pub_", ""))
    // it's valid, OR if the signature is generated by the user in the Sign panel.
    
    // We search the simulated logic:
    const inferredPrvKey = "prv_" + verifyPublicKey.replace("pub_", "");
    const expectedSig = simpleHash(verifyMessage + inferredPrvKey);
    
    if (verifySignature === expectedSig || verifySignature === generatedSignature) {
      setVerificationResult("VALID");
      toast.success("Signature check PASSED! Authenticity guaranteed.", { icon: "✅" });
    } else {
      setVerificationResult("INVALID");
      toast.error("Signature check FAILED! Message or key tampered.", { icon: "❌" });
    }
  };

  return (
    <div className="space-y-8 max-w-7xl mx-auto">
      <div>
        <h2 className="text-2xl font-bold text-slate-100 tracking-wide font-mono">CRYPTOGRAPHIC PLAYGROUND</h2>
        <p className="text-xs text-slate-500 font-mono font-semibold uppercase tracking-wider mt-1">
          Interactive workspace for HD Wallet seed derivation & asymmetric keys signatures
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        
        {/* Left Side: Seed Phrase & HD Wallet */}
        <div className="cyber-glass border border-white/5 rounded-2xl p-6 space-y-6">
          <div>
            <h3 className="text-sm font-bold text-slate-200 flex items-center gap-2 mb-1">
              <Key className="text-cyber-cyan w-4 h-4" /> 12-Word Mnemonic HD Engine
            </h3>
            <p className="text-[10px] text-slate-500 font-mono">Generate seed phrases and derive hierarchical accounts</p>
          </div>

          {/* Word list view */}
          <div className="grid grid-cols-3 sm:grid-cols-4 gap-3">
            {mnemonic.length === 0 ? (
              <div className="col-span-4 py-8 rounded-xl border border-dashed border-white/10 text-center text-slate-600 font-mono text-xs">
                No seed phrase loaded
              </div>
            ) : (
              mnemonic.map((word, i) => (
                <div key={i} className="p-2.5 rounded-lg border border-white/5 bg-slate-900/60 flex items-center gap-2 font-mono text-xs">
                  <span className="text-[9px] text-slate-500 font-bold">#{i + 1}</span>
                  <span className="text-slate-300 font-semibold">{word}</span>
                </div>
              ))
            )}
          </div>

          <div className="flex gap-3">
            <button
              onClick={handleGenerateMnemonic}
              className="flex-1 py-2.5 bg-slate-900/60 hover:bg-slate-800/80 border border-white/5 hover:border-white/10 rounded-xl text-xs font-mono font-bold text-slate-300 transition-all cursor-pointer"
            >
              GENERATE NEW SEED
            </button>
            <button
              onClick={handleDeriveKeys}
              disabled={mnemonic.length === 0}
              className="flex-1 py-2.5 bg-cyber-cyan hover:bg-cyber-cyan/90 text-slate-950 rounded-xl text-xs font-mono font-bold transition-all disabled:opacity-50 cursor-pointer"
            >
              DERIVE HD ACCOUNTS
            </button>
          </div>

          {/* Derivation input */}
          {mnemonic.length > 0 && (
            <div className="space-y-1.5">
              <label className="block text-[10px] font-mono text-slate-500 font-bold uppercase">Derivation Path</label>
              <input
                type="text"
                value={derivationPath}
                onChange={(e) => setDerivationPath(e.target.value)}
                className="w-full bg-slate-900/40 border border-white/10 rounded-xl py-2 px-3 text-xs text-slate-300 font-mono focus:outline-none focus:border-cyber-cyan focus:ring-1 focus:ring-cyber-cyan/20"
              />
            </div>
          )}

          {/* Derived output display */}
          {derivedWallet && (
            <div className="p-4 rounded-xl border border-cyber-cyan/10 bg-cyber-cyan/2 space-y-3 font-mono text-[10px]">
              <div className="flex justify-between border-b border-cyber-cyan/10 pb-1.5 text-cyber-cyan font-bold">
                <span>DERIVED ACCOUNT #0</span>
                <span className="text-[8px] bg-cyber-cyan/10 px-1.5 py-0.5 rounded">ECDSA / SECP256K1</span>
              </div>
              <div className="space-y-2">
                <div>
                  <span className="text-slate-500 block mb-0.5">Public Address</span>
                  <div className="flex justify-between items-center bg-black/30 p-1.5 rounded border border-white/5">
                    <span className="text-slate-200 select-all">{derivedWallet.address}</span>
                    <button onClick={() => copyToClipboard(derivedWallet.address, "Derived Address")} className="text-slate-500 hover:text-cyber-cyan bg-transparent border-0 cursor-pointer">
                      <Copy className="w-3 h-3" />
                    </button>
                  </div>
                </div>
                <div>
                  <span className="text-slate-500 block mb-0.5">Public Key (Compressed)</span>
                  <div className="flex justify-between items-center bg-black/30 p-1.5 rounded border border-white/5">
                    <span className="text-slate-400 select-all truncate max-w-[250px]">{derivedWallet.publicKey}</span>
                    <button onClick={() => copyToClipboard(derivedWallet.publicKey, "Derived Public Key")} className="text-slate-500 hover:text-cyber-cyan bg-transparent border-0 cursor-pointer">
                      <Copy className="w-3 h-3" />
                    </button>
                  </div>
                </div>
                <div>
                  <span className="text-slate-500 block mb-0.5">Private Key (Secret)</span>
                  <div className="flex justify-between items-center bg-black/30 p-1.5 rounded border border-white/5">
                    <span className="text-slate-400 select-all truncate max-w-[250px]">{derivedWallet.privateKey}</span>
                    <button onClick={() => copyToClipboard(derivedWallet.privateKey, "Derived Private Key")} className="text-slate-500 hover:text-cyber-cyan bg-transparent border-0 cursor-pointer">
                      <Copy className="w-3 h-3" />
                    </button>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Right Side: Message Signer & Signature Verifier */}
        <div className="space-y-8">
          
          {/* Message Signer Form */}
          <div className="cyber-glass border border-white/5 rounded-2xl p-6 space-y-4">
            <div>
              <h3 className="text-sm font-bold text-slate-200 flex items-center gap-2 mb-1">
                <FileText className="text-cyber-purple w-4 h-4" /> Message Signer Terminal
              </h3>
              <p className="text-[10px] text-slate-500 font-mono">Sign any message using private keys to authorize transactions</p>
            </div>

            <form onSubmit={handleSign} className="space-y-4">
              <div>
                <label className="block text-[10px] font-mono text-slate-400 font-bold uppercase mb-1">Raw Message</label>
                <textarea
                  value={signMessage}
                  onChange={(e) => setSignMessage(e.target.value)}
                  placeholder="e.g. Transfer 50 CLD to CLD_A9B2F..."
                  rows={2}
                  className="w-full bg-slate-900/60 border border-white/10 rounded-xl py-2 px-3 text-xs text-slate-100 font-mono focus:outline-none focus:border-cyber-purple transition-all resize-none"
                />
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-[10px] font-mono text-slate-400 font-bold uppercase mb-1">Private Key</label>
                  <input
                    type="password"
                    value={signPrivateKey}
                    onChange={(e) => setSignPrivateKey(e.target.value)}
                    placeholder="prv_..."
                    className="w-full bg-slate-900/60 border border-white/10 rounded-xl py-2 px-3 text-xs text-slate-100 font-mono focus:outline-none focus:border-cyber-purple transition-all"
                  />
                </div>
                <div className="flex items-end">
                  <button
                    type="submit"
                    className="w-full bg-cyber-purple hover:bg-cyber-purple/90 text-slate-100 font-bold tracking-wider py-2.5 rounded-xl text-xs font-mono transition-all border border-cyber-purple/40 cursor-pointer"
                  >
                    SIGN MESSAGE
                  </button>
                </div>
              </div>
            </form>

            {generatedSignature && (
              <div className="p-3.5 rounded-xl border border-cyber-purple/10 bg-cyber-purple/2 space-y-2 font-mono text-[10px]">
                <div className="flex justify-between items-center text-cyber-purple font-bold">
                  <span>GENERATED SIGNATURE (HEX)</span>
                  <button
                    onClick={() => copyToClipboard(generatedSignature, "Signature")}
                    className="text-slate-500 hover:text-cyber-purple bg-transparent border-0 cursor-pointer"
                  >
                    <Copy className="w-3.5 h-3.5" />
                  </button>
                </div>
                <span className="text-slate-300 break-all leading-relaxed select-all">{generatedSignature}</span>
              </div>
            )}
          </div>

          {/* Signature Verifier Form */}
          <div className="cyber-glass border border-white/5 rounded-2xl p-6 space-y-4">
            <div>
              <h3 className="text-sm font-bold text-slate-200 flex items-center gap-2 mb-1">
                <ShieldCheck className="text-cyber-emerald w-4 h-4" /> Signature Integrity Verifier
              </h3>
              <p className="text-[10px] text-slate-500 font-mono">Verify if a signature has been tampered or matches public keys</p>
            </div>

            <form onSubmit={handleVerify} className="space-y-4 font-mono text-xs">
              <div>
                <label className="block text-[10px] font-bold text-slate-400 uppercase mb-1">Raw Message</label>
                <input
                  type="text"
                  value={verifyMessage}
                  onChange={(e) => setVerifyMessage(e.target.value)}
                  placeholder="Paste message to verify..."
                  className="w-full bg-slate-900/60 border border-white/10 rounded-xl py-2.5 px-3 text-xs text-slate-100 focus:outline-none focus:border-cyber-emerald transition-all"
                />
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-[10px] font-bold text-slate-400 uppercase mb-1">Public Key</label>
                  <input
                    type="text"
                    value={verifyPublicKey}
                    onChange={(e) => setVerifyPublicKey(e.target.value)}
                    placeholder="pub_..."
                    className="w-full bg-slate-900/60 border border-white/10 rounded-xl py-2.5 px-3 text-xs text-slate-100 focus:outline-none focus:border-cyber-emerald transition-all"
                  />
                </div>
                <div>
                  <label className="block text-[10px] font-bold text-slate-400 uppercase mb-1">Signature</label>
                  <input
                    type="text"
                    value={verifySignature}
                    onChange={(e) => setVerifySignature(e.target.value)}
                    placeholder="Paste hex signature..."
                    className="w-full bg-slate-900/60 border border-white/10 rounded-xl py-2.5 px-3 text-xs text-slate-100 focus:outline-none focus:border-cyber-emerald transition-all"
                  />
                </div>
              </div>

              <button
                type="submit"
                className="w-full bg-cyber-emerald text-slate-950 font-bold tracking-wider py-2.5 rounded-xl text-xs transition-all hover:bg-cyber-emerald/90 cursor-pointer"
              >
                VERIFY SIGNATURE AUDIT
              </button>
            </form>

            {/* Verification Result Badge */}
            {verificationResult && (
              <div className={`p-4 rounded-xl border flex items-center gap-3 font-mono text-xs ${
                verificationResult === "VALID"
                  ? "border-cyber-emerald/20 bg-cyber-emerald/5 text-cyber-emerald shadow-[0_0_15px_rgba(16,185,129,0.08)]"
                  : "border-cyber-rose/20 bg-cyber-rose/5 text-cyber-rose shadow-[0_0_15px_rgba(244,63,94,0.08)]"
              }`}>
                {verificationResult === "VALID" ? (
                  <>
                    <ShieldCheck className="w-6 h-6 shrink-0 text-cyber-emerald animate-pulse" />
                    <div>
                      <h4 className="font-bold">SIGNATURE AUDIT SECURED</h4>
                      <p className="text-[10px] text-slate-400 mt-0.5 leading-tight">The signature matches the public key and message. Integrity is verified.</p>
                    </div>
                  </>
                ) : (
                  <>
                    <ShieldAlert className="w-6 h-6 shrink-0 text-cyber-rose animate-bounce" />
                    <div>
                      <h4 className="font-bold">SIGNATURE AUDIT FAILURE</h4>
                      <p className="text-[10px] text-slate-400 mt-0.5 leading-tight">The signature is invalid. The key, message, or signature has been tampered with.</p>
                    </div>
                  </>
                )}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
