input {
  file {
    path => "/usr/share/logstash/logs/cipherledger-audit*.json"
    start_position => "beginning"
    codec => "json"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "cipherledger-audit-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
